import {
  BadgeCheck,
  BookOpen,
  CalendarDays,
  ClipboardCheck,
  FileText,
  FileCheck,
  Headphones,
  LayoutDashboard,
  LibraryBig,
  LogIn,
  Megaphone,
  MessageCircleQuestion,
  ReceiptText,
  SearchCheck,
  ShieldCheck,
  SlidersHorizontal,
  User,
  UserCog,
  Users,
  Wallet,
  Award,
} from "lucide-react";

export const menuIcon = {
  dashboard: LayoutDashboard,
  login: LogIn,
  book: BookOpen,
  team: Users,
  user: User,
  settings: SlidersHorizontal,
  finance: Wallet,
  helpdesk: MessageCircleQuestion,
  contentReview: FileCheck,
  audit: ShieldCheck,
  certificate: Award,
  announcement: Megaphone,
  admission: ClipboardCheck,
  calendar: CalendarDays,
  document: FileText,
  library: LibraryBig,
  review: SearchCheck,
  support: Headphones,
  transaction: ReceiptText,
  verified: BadgeCheck,
  userSettings: UserCog,
} as const;
